version: "3.8"
services:
  sesac-codingon:
    volumes: 
      - /app/node_modules
      - ./:/app/
    build: 
      context: .
    ports:
      - "8000:8000"
  node:
    image: "node:16"
    working_dir: /usr/src/app
    volumes:
    # 내가 수정한 걸 바로 반영하기 위해 사용
    # ./ : 지금 내가 수정하고 있는 경로
    # /usr/src/app : 내가 수정한 걸 반영할 컨테이너 경로(working_dir)
      - ./:/usr/src/app
    ports:
      - "8001:8000"
    command: bash -c "npm install && node index"